model_list:
  - model_name: qwen2.5-coder:14b.local
    litellm_params:
      model: os.environ/LITELLM_OLLAMA_MODEL
      api_base: os.environ/OLLAMA_HOST
      api_key: "not-used"  # Internal key for local model  gemma3:4b
  - model_name: gemma3:4b.local
    litellm_params:
      model: ollama/gemma3:4b
      api_base: os.environ/OLLAMA_HOST
      api_key: "not-used"  # Internal key for local model  gemma3:4b

general_settings:
  master_key: os.environ/LITELLM_MASTER_KEY
